server:
  port: 7002
spring:
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000


  session:
    store-type: redis