server:
  port: 8011
#Rabbitmq
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: Message
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloudemail?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&serverTimezone=GMT%2b8
    username: root
    password: 137286
  mail:
    host: smtp.163.com
    username: xiexinquan520@163.com
    password: QKFUWKSRMXJHUZZG
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true