server:
  port: 8001

spring:
  application:
    name: payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&serverTimezone=GMT%2b8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 118.89.133.157:8848
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#logging:
#  level:
#    com.com.quan.dao: debug
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.com.quan.entity


  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
  mail:
    host: smtp.163.com
    username: xiexinquan520@163.com
    password: QKFUWKSRMXJHUZZG
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#自定义属性
com:
  quan:
    ftp:
      host: 118.89.133.157
      port: 21
      username: com.quan
      password: huanting
      filepath: /data/nginx/html
    web:
      host: 118.89.133.157
      port: 81
